security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/admin/, role: ROLE_ADMIN }

    firewalls:

        login:
            pattern:                        ^/(login|reset-request|send-email|check-email)$
            provider:                       fos_userbundle
            anonymous:                      true
        main:
            pattern:    ^/
            #form_login:
            #    check_path: /login_ckeck
            #    login_path: /login
            #    provider: fos_userbundle
            #logout:
            #    path:   /logout
            #    target: /
            #anonymous: ~
            form_login:
                provider: fos_userbundle
                default_target_path: /
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    false









